rapport.pdf:	rapport.tex
	pdflatex rapport.tex
#	makeglossaries rapport.glo
#	pdflatex rapport.tex
#	pdflatex rapport.tex

clean: 
	rm -f *.glo *.gls *.aux *.tex.backup *.acn *.ist *.toc *.log *.out *.glg *.lot
#include LaTex.mk
#rome.pdf: rome.glo rome.tex 
#	makeglossaries rome.glo
#	pdflatex rome.tex
#	pdflatex rome.tex
#
#rome.glo:
#	pdflatex rome.tex
